version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    command: node index.js
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
  admin:
        build:
          context: ./admin
          dockerfile: Dockerfile
        ports:
          - "5174:80"
        depends_on:
          backend:
            condition: service_started
        restart: unless-stopped
